---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: my-inference-service-4
  namespace: kubeflow-user-example-com
  annotations:
       sidecar.istio.io/inject: "false"
  labels:
    app: nginx
spec:
  predictor:
    containers:
      - image: docker.io/rahulyerme1234/aiml-model:1
        ports:
          - containerPort: 5000
